---
- name: Generate router config files
  template: src=router-template.j2 dest={{ confdir }}/routers/{{item.hostname}}.cfg
  with_items: "{{ router_variables }}"

- name: Generate srx config files
  template: src=srx-template.j2 dest={{ confdir }}/srx/{{item.hostname}}.cfg
  with_items: "{{ srx_variables }}"

